### ISSUE TITLE
Can't build with Flutter 2.5.0

### ISSUE THREAD

**Issue by poka-IT** [olayemii/crypto-dashboard#1]
I got a lot of errors here due to dependencies: https://paste.ofcode.org/Bw6jT3MSB8mJFH8pDGbzSv

Pub get is OK, no errors in vscode before building (just a ununsed import:
`Unused import: 'package:crypto_dashboard/pages/coin_detail/coin_detail.dart`

I'm on Flutter 2.5.0 on linux.

**Comment by olayemii** [comment]
@poka-IT did you try running `flutter clean` before trying to run?

**Comment by poka-IT** [comment]
Yes sure i did.

**Comment by olayemii** [comment]
@poka-IT 31098e9   should fix that, it's a dependency issue..pull and retry..Thanks.
